// import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./[components]/Nav";
// import Login from "./[components]/Login";

// const inter = Inter({ subsets: ["latin"] });
import AuthProvider from "./[components]/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="bg-gray-100">
          <Nav />
          {/* <Login /> */}
          <div className="m-2 min-h-screen">{children}</div>
        </body>
      </AuthProvider>
    </html>
  );
}
